# 查找头文件目录
FIND_PATH(MYSQL_INCLUDE_DIR
		mysql.h
		$ENV{MYSQL__HOME}/include
)

MACRO(FIND_MYSQL_LIB LIBNAME LIBFILE)
	FIND_LIBRARY(${LIBNAME}
		NAMES LIBFILE PATHS $ENV{MYSQL__HOME}/lib
     )
ENDMACRO(FIND_MYSQL_LIB LIBNAME LIBFILE)

# 查找库
FIND_MYSQL_LIB(MYSQL_LIBRARY libmysql)
FIND_MYSQL_LIB(MYSQL_LIBRARY_DEBUG libmysql)

IF(MYSQL_INCLUDE_DIR)
	SET(MYSQL_FOUND TRUE)
ENDIF(MYSQL_INCLUDE_DIR)